### ISSUE TITLE
Missing authorization header

### ISSUE THREAD

**Issue by sailesh** [antarctica/flask-azure-oauth#10]
Hi, 

I've set up a minimal application from doco as below. When I visit a protected route, http://localhost:5000/api/time, I get an error below. Am I missing something obvious? 

Much appreciated.

`{"errors": [{"id": "30917ee6-20ce-4508-bcc7-f0157c74xxxx", "status": 401, "title": "Missing authorization header", "detail": "Ensure your request includes an 'Authorization' header and try again"}]}`

```
import flask
import arrow
from os import environ
from flask_azure_oauth import FlaskAzureOauth

app = flask.Flask(__name__)

app.config['AZURE_OAUTH_TENANCY'] = environ.get('AZURE_OAUTH_TENANCY')
app.config['AZURE_OAUTH_APPLICATION_ID'] = environ.get( 'AZURE_OAUTH_APPLICATION_ID')

auth = FlaskAzureOauth()
auth.init_app(app)

@app.route("/api/time")
@auth()
def time():
    return {"time": str(arrow.now())}


if __name__ == "__main__":
    app.run(host='0.0.0.0')
```

**Comment by felnne** [comment]
Hi @sailesh,

How are you generating the access token to pass to the protected route?

This library only implements the verification of existing tokens, rather than issuing them and including them in requests. For those tasks you'd need to use something like the [Microsoft Authentication Library (MSAL) for Python] (https://github.com/AzureAD/microsoft-authentication-library-for-python) package.

**Comment by sailesh** [comment]
Hi Felix @felnne,
Thanks for the tip. I was able to get it working by following https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-python-webapp
