### ISSUE TITLE
Optional decorator for @auth

### ISSUE THREAD

**Issue by doctormohamed** [antarctica/flask-azure-oauth#22]
Hi, 
In some cases (development or whatever), we need to disable the auth, or need to use other auth decorators in some other cases. Can you add a new parameter to auth, that for example: optional=False, then it will bypass the authentication for that route?

`@app.auth(optional=False)`

**Comment by felnne** [comment]
Hi @doctormohamed,

I don't plan to add this sorry - partly because of time I have available, but also because this feels like an easy way for things to go wrong (being left enabled etc.).

There is an existing way to effectively do what you're asking for - using local tokens signed by a local key set - https://github.com/antarctica/flask-azure-oauth#testing-support. That's intended for use in testing situations but could be adapted to work for a development environment as well if you wanted.

Alternatively, you could create a wrapper around the AuthLib decorator with the extra parameter and either return straight away if the testing mode is enabled, or otherwise pass through to the real provider.

Sorry that probably isn't the answer you're looking for but hope those alternatives help.

**Comment by doctormohamed** [comment]
Thanks @felnne por quick reply!

Actually I went for the second option, here is the solution for whoever needs it:


`def enable_decorator(decorator, condition):
    def conditional_decorator(fn):
        dec = decorator(fn)

        def wrapper(*args, **kw):
             if condition:
                 return dec(*args, **kw)
             return fn(*args, **kw)
        wrapper.__name__ = fn.__name__
        return wrapper
    return conditional_decorator`

USAGE:
`@enable(app.auth(), enable_auth)`

**Comment by felnne** [comment]
@doctormohamed, great, I'm going to close this issue in that case.
