### ISSUE TITLE
Not able to authorize

### ISSUE THREAD

**Issue by kimrunar** [antarctica/flask-azure-oauth#4]
I get this error when trying to authenticate my access-token. 

{"errors":[{"id":"620b24e5-2d1e-416b-a0f8-1d9717b23f9f","status":401,"title":"Invalid token signature","detail":"The JSON Web Token (JWT) used as a token could be verified as authentic. Ensure you are using the correct token and try again, or contact support."}]}

If i run curl with same token i receive the data and it is authenticated.:
curl -X GET -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub*****************_Uuyua2Sz1KS8E-DyGVvoCnze607eyUY5ngVeqXj_3RetKUQ" 'https://graph.microsoft.com/v2.0/me'

The code i'm using is just like the minimal example provided. 
Any help? 

Thanks.

**Comment by felnne** [comment]
Hi @kimrunar,

Sorry about that, that error should only occur if the JWKS doesn't match your tenancy, or the key for the tenancy has been rotated out if the application was already running.

Could you let me know the authorise endpoint you're calling to generate the JWT?

**Comment by kimrunar** [comment]
That would be this one: 
https://login.microsoftonline.com/294c7ede-2387-42ab-bbff-e5eb67ca3aee/v2.0

**Comment by kimrunar** [comment]
actually. its the jose jwt.decode() in tokens..py which fails with badsignatureError.

**Comment by felnne** [comment]
Hi @kimrunar,

Sorry for the delay in replying,

That's weird, as this package should fetch the key set specific to your tenancy. I've only encountered that error you're getting when using the TestJWT which uses a different (random) signing key intentionally.

Off hand I'm not sure what could be causing this to happen, are you able to decode a woken and check the `kid` claim matches one of the keys in the JWKS for the tenancy where your application is registered (and that you've set in `app.config["AZURE_OAUTH_TENANCY"]`)?

**Comment by janusch** [comment]
Hi,
I am getting the same error message. When i decoded the access token that I wanted to authorize with it shows that it is version 1.0 Could it be that only version 2 is supported?

**Comment by kimrunar** [comment]
> Hi,
> I am getting the same error message. When i decoded the access token that I wanted to authorize with it shows that it is version 1.0 Could it be that only version 2 is supported?

Some time since i had this issue now, but I think that was the issue yes. i had to specify version 2 in the manifest..

**Comment by janusch** [comment]
Hi,
thank you @kimrunar for your reply. 

I am still banging my head against this issue. I changed the manifest file to issue a version 2 token, but somehow that did not change anything. The token is still version 1. I found a github issue that describes the problem I am having, but no clear solution is pointed out. [Link](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/844) 

Is protecting the flask api with this library and authenticating a client javascript application user with msal.js a valid use case on how flask-azure-oauth can be used?

Is there a way to change the issuer of the token in flask-azure-oauth to the version 1 oauth endpoint? The issuer for the access token I get is always https://sts.windows.net/<tenantId>, somehow flask-azure-oauth needs to handle that it is coming from a version 1 endpoint.

Any insights or debug tips would be greatly appreciated!

**Comment by felnne** [comment]
Hi @janusch,

Sorry for the long delay in replying to you about this issue.

To clarify, currently this library does require a v2 token (in part because it expects to validate a list of approved applications via the `azp` claim). However I will make that check optional, in which case a V1 token should work as well (I think it makes sense to support both it just wasn't an issue we've encountered up to now).

> Is protecting the flask api with this library and authenticating a client javascript application user with msal.js a valid use case on how flask-azure-oauth can be used?

I would say that is definitely a valid use case. The client shouldn't matter but clearly Microsoft's recommend library should work. Personally I've used the Python version of MSAL which has worked, however I am using V2 tokens.

I've also found the tokens version confusing as the URL doesn't seem to make a difference to get a V2 token (i.e. if you use the V2 endpoint listed in Azure you still get a V1 token). Changing the manifest will work but it needs to the app registration representing the client application, rather than the registration representing the (Flask) app you're protecting using this library.

I'm currently integrating this library into a new project that will require some new features/changes so I will make the changes needed to support V1 tokens at the same time. However a won't be able to do that for a few weeks.

**Comment by janusch** [comment]
Hi @felnne ,
thank you very much for replying to this issue. Your reply shed a lot of light on my issue and I am now confident that I might be able to resolve the issue by refactoring the client to use `@azure/msal-browser` instead of `msal.js`. I hope that way I will acquire a V2 token that can be used for authorisation. 

I will let you know if that resolves the issue.

Keep up the great work!

**Comment by felnne** [comment]
Hi @janusch,

For reference, I've had some time today to work on this package and have added support for version 1.0 tokens directly. 

This may be too late and you've already changed your code but if not, I've made a test build that adds support for that (along with other changes) below. If this issue is still relevant hopefully that fixes the problem.

https://test.pypi.org/project/flask-azure-oauth/0.4.1.post17.dev0/

A full list of changes in the upcoming version is available here:

https://github.com/antarctica/flask-azure-oauth/blob/master/CHANGELOG.md#unreleased

**Comment by felnne** [comment]
@kimrunar,

Sorry for not replying to this issue for so long but to check, does your reply here mean your issue was fixed by moving to version 2.0 tokens?

> > Hi,
> > I am getting the same error message. When i decoded the access token that I wanted to authorize with it shows that it is version 1.0 Could it be that only version 2 is supported?
> 
> Some time since i had this issue now, but I think that was the issue yes. i had to specify version 2 in the manifest..

**Comment by janusch** [comment]
Hi @felnne,
Great work! 
Thank you very much for adding support for V1 tokens. I have finally gotten it to work with refactoring the client to use V2 tokens, but I am sure it will will be handy to support V1 as well.

I got one more question which is not related to this issue, I think I will just create a separate issue for that.

Thank you again for creating and maintaining this package!

I believe this issue can now be closed.

**Comment by felnne** [comment]
A new version of this package has been released which addresses numerous issues with token versions and app registrations.

Without knowing the exact cause of this issue I don't know if this release will address the specific issues of this case. If it doesn't please re-open this issue.

https://pypi.org/project/flask-azure-oauth/0.5.0/
