### ISSUE TITLE
Cannot authorize in test mode for Client Credential Flow without setting AZURE_OAUTH_CLIENT_APPLICATION_IDS

### ISSUE THREAD

**Issue by adammartin-mednax** [antarctica/flask-azure-oauth#5]
I was trying out flask-azure-oauth to replace our homebrewed version.  Out of the gates, I hit a very odd scenario.  While in TESTING = True mode I seem to have to set app.config['AZURE_OAUTH_CLIENT_APPLICATION_IDS'] to an array of acceptable Client Id's or I am unable to authorize a client.

Per the README my simple use case I'm trying to make work is:

> To restrict a route to any valid user or client application (authentication):
> - add the resource protector as a decorator (auth in this example) - for example the /protected route

In our code, we have initialized the app as documented:
```
    <snip>
    app.config['AZURE_OAUTH_TENANCY'] = os.environ['AD_TENANT']
    app.config['AZURE_OAUTH_APPLICATION_ID'] = os.environ['RESOURCE_ID']
    <snip>
    if os.environ['AD_TEST_CONFIG'] and os.environ['AD_TEST_CONFIG'] == 'True':
        app.config['TESTING'] = True

    <snip>
    auth = FlaskAzureOauth()
    auth.init_app(app)
```

On our endpoint we have added the appropriate security:
```
    @auth()
    <snip>
    def post(self):
```

On our unit testing time we are setting it to test mode as specified `os.environ['AD_TEST_CONFIG'] = 'True'`

In our test we have followed the prescribed mechanism for getting a test token:
```
        token = TestJwt(app=test_app)
        # found out need to do test.dumps() to get the token ... docs appear to be wrong raw token is a python object
        headers = {'authorization': f"bearer { token.dumps() }"} 
        response = client.post(url, json=request, headers=headers)
```

What we found is the ONLY way to get the test to go green was to set the client ids to include the id client we are calling with!  In this case the client and the resource are the same so we leverage that in our production code:
```
    app.config['AZURE_OAUTH_CLIENT_APPLICATION_IDS'] = [os.environ['RESOURCE_ID']]
```

This seems so very very wrong.

Please help!  What are we doing incorrectly here?  I don't want to make my application know the client ids of every application who wants to use it ... that's what we want OAuth to do and eventually manage via scopes.

Thanks!

**Comment by felnne** [comment]
Hi @adammartin-mednax,

Sorry for the delayed reply,  I should start by saying that the testing elements of this project are going to be revisited now that I know more about test frameworks. Notably this will mean mocking the standard JWT class (possibly with the TestJWT class) but I'll need to think about how to expose that for others to use when testing as you are, and we do.

To clarify your comment about `token.dumps()`, sorry that was an oversight on my part, I will correct that in the documentation.

For your main question about having to set `AZURE_OAUTH_CLIENT_APPLICATION_IDS`, that is mandatory at the moment but I can see that should be optional instead.

We do that because it adds extra protection before a new client application will be allowed - i.e. someone would need to change the code to allow a new client which would be visible in version control history.

We also use it in situations where a user may be authorised but the client can't be trusted for some reason.

I'm not an Azure expert so there may well be a way for Azure to take into account the application a user is using before allowing a scope they're entitled to to be included in the access token but this way has worked for what we need currently.

I hope that explains why this happens and that you're not missing anything. In terms of fixing this, would making that hard-coded list optional be sufficient because I'd be happy to make that change if so.

**Comment by adammartin-mednax** [comment]
Awesome yeah makes a boatload of sense.

I think our next step is to wait for the modification to `AZURE_OAUTH_CLIENT_APPLICATION_IDS` ... I've managed to deal with some of the 'issues' of testing for the time (not in an ideal fashion but in a functional one).  The big miss right now is that in our use case we are blocked by that requirement of the application ids.

Really thank you for the update and have a great holiday weekend if you are in the US ;)

**Comment by felnne** [comment]
Hi @adammartin-mednax,

Apologies for the long reply, I've finally had some time today to work on the next version of this package and hopefully fix this issue.

I've made a test build that makes the `azp` claim, and it's trusted list of applications, optional (along with other changes) here:

https://test.pypi.org/project/flask-azure-oauth/0.4.1.post17.dev0/

Before I make this a real release could you check this does what you need?

A full list of changes in the upcoming version is available here:

https://github.com/antarctica/flask-azure-oauth/blob/master/CHANGELOG.md#unreleased

Note that if you are using this for tests you will need to make changes (as noted in the breaking section in the change log), the example tests in the README have been updated to hopefully show what to do but let me know if they don't.

https://github.com/antarctica/flask-azure-oauth/blob/master/README.md#testing-support

**Comment by felnne** [comment]
Support for this feature has been added in the latest published release. Please re-open this issue if you still face issues.

https://pypi.org/project/flask-azure-oauth/0.5.0/
